### ISSUE TITLE
Slow interactions under medium-size profiles

### ISSUE THREAD

**Issue by javierluraschi** [r-lib/profvis#87] opened 2017-08-02 18:21 UTC
Medium-size profiles are taking long to load, drag the slider, and switch back to flame-graph view. I don't think this is a regression.

See: http://rpubs.com/jluraschi/profiler-sparklyr-test

<img width="1440" alt="screen shot 2017-08-02 at 11 20 21 am" src="https://user-images.githubusercontent.com/3478847/28888214-a2cbb55c-7774-11e7-8b0d-a0b01d286f9c.png">

For tab switching, the bottleneck seems to be constructing the SVG, there is a [Forced reflow](https://developers.google.com/web/fundamentals/performance/rendering/avoid-large-complex-layouts-and-layout-thrashing#avoid-forced-synchronous-layouts) warning while getting a profile of the profile:

<img width="1440" alt="screen shot 2017-08-02 at 11 18 21 am" src="https://user-images.githubusercontent.com/3478847/28888141-61af2ba8-7774-11e7-84fd-fd600ddd5a07.png">

**Comment by Fuco1** [comment] 2019-04-10 10:30
Is there a way to generate the profile without the bottom part.  I honestly have no idea how to use it.  My profile file is 45 megabytes and I only use the top part where the code is shown.

**Comment by hadley** [comment] 2024-08-21 21:27
Duplicate of #104

**Closed by hadley** 2024-08-21 21:27 UTC
Labels: performance
